### ISSUE TITLE
Adding modbus registers

### ISSUE THREAD

**Issue by cappadanna** [toringer/home-assistant-heru#6]
Just wanted to share the modbus config I have been using for my heru. Saw it included some registers that you might be able to add to this integration (on/off mode, summer cooling mode etc.) I have not created this config but I can unfortunatley not remember where I found it:

```
# Binary sensor , input type (discrete_input or coil)
# Sensor (register_type input or holding)
# 0 - coil, 1 - discrete_input, 3 - input register, 4- holding register

#HA adress = Heru adress -1

######################################
#########       SWITCHES     #########
######################################

        switches:
        
#### COIL ####

          - name: FTX Drift
            address: 0
            write_type: coil
            verify:
            scan_interval: 10

          - name: FTX Övertryck
            address: 1
            write_type: coil
            verify:
            scan_interval: 10

          - name: FTX Boost
            address: 2
            write_type: coil
            verify:
            scan_interval: 10

          - name: FTX Borta
            address: 3
            write_type: coil
            verify:
            scan_interval: 10
            
          - name: FTX Återställ Larm
            address: 4
            write_type: coil
            verify:
            scan_interval: 10
            
#### HOLDING ####
            
          - name: FTX Sommarkyla
            address: 18
            write_type: holding
            command_on: 1
            command_off: 0
            lazy_error_count: 3
            verify:
            scan_interval: 60
            
          - name: FTX Elvärme
            address: 66
            write_type: holding
            command_on: 1
            command_off: 0
            lazy_error_count: 3
            verify:
            scan_interval: 60

######################################
######       BINARY SENSORS     ######
######################################

        binary_sensors:

# #### COIL ####

# Use as switch instead
#           - name: FTX Drift
#             address: 0
#             input_type: coil
#             device_class: power
#             scan_interval: 60
#             lazy_error_count: 3

#### DISCRETE_INPUT - ALARM REGISTERS ####

          - name: FTX Fire Alarm
            address: 9
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Rotor Alarm
            address: 10
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Freeze Alarm
            address: 12
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Low Supply Alarm
            address: 13
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Low Rotor Temp Alarm
            address: 14
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Temp Sensor Open Alarm
            address: 17
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Temp Sensor Short Alarm
            address: 18
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Supply Fan Alarm
            address: 20
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Exhaust Fan Alarm
            address: 21
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Freeze Protection B
            address: 25
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Freeze Protection A
            address: 26
            input_type: discrete_input
            device_class: safety
            scan_interval: 60
            lazy_error_count: 3

#### DISCRETE_INPUT - STATES ####

        #   - name: FTX Heating
        #     address: 29
        #     input_type: discrete_input
        #     device_class: heat
        #     scan_interval: 60
        #     lazy_error_count: 3

        #   - name: FTX Recovery Heat Cold
        #     address: 30
        #     input_type: discrete_input
        #     device_class: heat
        #     scan_interval: 60
        #     lazy_error_count: 3

        #   - name: FTX Cooling
        #     address: 31
        #     input_type: discrete_input
        #     device_class: heat
        #     scan_interval: 60
        #     lazy_error_count: 3


######################################
#########       SENSORS     ##########
######################################

        sensors:
          - name: FTX Ute
            unit_of_measurement: '°C'
            address: 1
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3
            precision: 1
            scale: 0.1

          - name: FTX Tilluft
            unit_of_measurement: '°C'
            address: 2
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3
            precision: 1
            scale: 0.1

          - name: FTX Frånluft
            unit_of_measurement: '°C'
            address: 3
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3
            precision: 1
            scale: 0.1

          - name: FTX Avluft
            unit_of_measurement: '°C'
            address: 4
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3
            precision: 1
            scale: 0.1

          - name: FTX Rotor
            unit_of_measurement: '°C'
            address: 6
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3
            precision: 1
            scale: 0.1
            
          - name: FTX Rum
            unit_of_measurement: '°C'
            address: 7
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3
            precision: 1
            scale: 0.1

          - name: FTX Filter
            unit_of_measurement: 'dagar'
            address: 19
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Tilluftsfläkt
            unit_of_measurement: '%'
            address: 24
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Frånluftsfläkt
            unit_of_measurement: '%'
            address: 25
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Tilluftsfläkt RPM
            unit_of_measurement: 'RPM'
            address: 26
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX Frånluftsfläkt RPM
            unit_of_measurement: 'RPM'
            address: 27
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3
            
          - name: FTX_Elvärme_255
            unit_of_measurement: ''
            address: 28
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3

          - name: FTX_Rotor_speed_255
            unit_of_measurement: ''
            address: 29
            data_type: int16
            input_type: 'input'
            scan_interval: 60
            lazy_error_count: 3


######################################
#########       CLIMATE     ##########
######################################
        
        climates:
          - name: Heru FTX
            address: 7 #Mätvärde rum
            data_type: int16
            input_type: 'input'
            scale: 1
            offset: 0
            precision: 1
            max_temp: 25
            min_temp: 15
            temp_step: 1
            target_temp_register: 1 #Börvärde tilluft
            scan_interval: 60
```
